Supplier
milton-pagan/disaster-storage-api pull request #10
Opened 2020-03-29 20:53 UTC by jesus1148

2020-03-29 21:12 UTC, milton-pagan commented on api/handlers/customer_handler.py
> +            result_dict.append(self.build_customer(record))
Por ahora esto está bien, pero en la proxima fase esto no va a ser necesario dado que psycopg te da la opción de utilizar algo que se llama un RealDictionaryCursor que ya te da los resultados como diccionario, por lo cual no habría que construirlos.

2020-03-29 21:31 UTC, milton-pagan requested changes
En general, se ve bastante bien, pero un detalle importante es que se te olvidó crear el usuario cuando creas alguna de sus subcategorias, y también te falta hacer todo lo de admin. Asegurate de leer los comentarios que hice.

2020-03-29 21:31 UTC, milton-pagan commented on api/handlers/customer_handler.py
> +        if customer and len(customer) == 5:
Estas verificando que tenga los arguments usando el length, que aunque es parcialmente correcto, aún podría traer errores. La mejor manera de verificar esto es usando un try/except block, por ejemplo:
```
try:
            customer_first_name = customer["customer_first_name"]
            customer_last_name = customer["customer_last_name"]
            customer_city = customer["customer_city"]
            latitude = customer["latitude"]
            longitude = customer["longitude"]
except KeyError:
            ErrorHandler().bad_request()
```
Esto lo que hace es intentar accesar los keys en el diccionario, y si encuentra que alguno no existe, quiere decir que no se pasaron los parametros necesarios y por tanto es un bad request.

Por ahora esto está bien, pero es algo que tener en cuenta para la próxima fase.

2020-03-29 21:31 UTC, milton-pagan commented on api/handlers/customer_handler.py
> +            if customer_first_name and customer_last_name and customer_city and latitude and longitude:
Por un error que me ocurrió a mi me di cuenta que estas verificaciones no funcionan, por que si por ejemplo resulta que latitude es 0, el if va a ser falso, aunque no debería serlo. En mi handler yo quite estas verificaciones, que en realidad no son necesarias si se hace el try/except block. De nuevo, por ahora está bien pero para la próxima fase hay que cambiarlo.

2020-03-29 21:31 UTC, milton-pagan commented on api/handlers/customer_handler.py
> +            customer_city = args.get("city")
Aquí debe haber un try/except block. Mira el próximo comentario.

2020-03-29 21:31 UTC, milton-pagan commented on api/handlers/customer_handler.py
> +    def insert_customer(self, customer):
**IMPORTANTE**

Se te olvido crear un user cuando añades un usuario. También se debe incluir el user id como haces con el location id, y para esto tienes que crear un user primero. Esto implica que también se debe incluir en los parametros que reciben todo lo que se necesita para crear un User. De hecho, nunca debería crearse un user solo, siempre va a ser el resultado de crear un customer, supplier o admin.

**Todo esto aplica a supppliers y admin también**

2020-03-29 22:23 UTC, jesus1148 commented on api/handlers/customer_handler.py
> +            result_dict.append(self.build_customer(record))
Super, va a ser más fácil.

2020-03-30 16:03 UTC, milton-pagan requested changes
Buen trabajo, solo unos pequeños detalles para arreglar. Asegurate de leer los comentarios.

2020-03-30 16:03 UTC, milton-pagan commented on api/handlers/user_handler.py
> +                result_dict["phone_id"] = phone_id
Habíamos acordado en que cada user tendría un solo telefono, entonces no debe ser un phone id sino el phone number.

2020-03-30 16:03 UTC, milton-pagan commented on api/dao/credit_card_dao.py
> +    def insert_credit_card(self, cc_type, cc_number, cc_exp, cc_sec_code):
Añadiste atributos que no están en el E-R, mantente solo con los que estan allí. No creo que sea necesario este nivel de detalle.

2020-03-30 16:03 UTC, milton-pagan commented on api/dao/admin_dao.py
> +        return []
Aqui falta añadir los resultados harcoded.

2020-03-30 23:53 UTC, jesus1148 commented on api/handlers/user_handler.py
> +                result_dict["phone_id"] = phone_id
Se me olvido cambiarlo, ya que eso lo habia hecho antes.

2020-03-30 23:55 UTC, jesus1148 commented on api/dao/credit_card_dao.py
> +    def insert_credit_card(self, cc_type, cc_number, cc_exp, cc_sec_code):
Es verdad, es que tengo impreso el ER antiguo y me deje llevar por ese, lo cambio enseguida.

2020-03-30 23:57 UTC, jesus1148 commented on api/dao/admin_dao.py
> +        return []
Okay.

2020-03-30 23:58 UTC, jesus1148 commented on api/dao/admin_dao.py
> +        return []
Alguna idea de que poner?

2020-03-31 18:56 UTC, milton-pagan requested changes
Pequeños detalles que arreglar antes del merge.

2020-03-31 18:56 UTC, milton-pagan commented on api/handlers/customer_handler.py
> +                    cc_id,
Me percaté que la relacion entre customer y credit card es 1-to-N, y el many side es credit card con total participation. Eso significa que customer no lleva cc_id, sino que credit card lleva el customer_id, hay que invertirlos.

2020-03-31 18:56 UTC, milton-pagan commented on api/handlers/user_handler.py
> +                result_dict["phone_id"] = phone_number
El string debe cambiar a phone_number también.

2020-03-31 18:56 UTC, milton-pagan commented on main.py
> +@app.route("/disasterStorage/users/admin", methods=["GET"])
Faltaría el delete y put aquí. En realidad no van a ser muy útiles pero solo por cuestión de tenerlo completo.

2020-03-31 20:13 UTC, milton-pagan approved these changes
Approved. Nice job.

2020-03-31 20:13 UTC, milton-pagan commented on api/handlers/supplier_handler.py
> +        return object_dict
Missing product_category.

2020-03-31 20:13 UTC, merged